sudo: required
services:
  - docker

before_install:
  - docker build -t alexioan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true alexioan/docker-react npm run test

deploy:
  provided: elasticbeanstalk
  region: "us-east-2"
  app: "Docker React"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-025063817354"
  bucket_path: "Docker React"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

